const CART_KEY="elinaCart";
const money=n=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF"}).format(n);
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch{return[]}}
function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartBadge()}
function updateCartBadge(){const count=getCart().reduce((s,i)=>s+(i.quantity||1),0);document.querySelectorAll("[data-cart-count]").forEach(el=>el.textContent=count)}
function addToCart(product){const cart=getCart();const same=cart.find(i=>i.id===product.id&&i.size===product.size);if(same)same.quantity=(same.quantity||1)+1;else cart.push({...product,quantity:1});saveCart(cart)}
function initProductPage(){const root=document.querySelector("[data-product]");if(!root)return;let size="";const main=document.querySelector("[data-main-image]");document.querySelectorAll("[data-thumb]").forEach(img=>img.addEventListener("click",()=>main.src=img.src));document.querySelectorAll("[data-size]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-size]").forEach(b=>b.classList.remove("active"));btn.classList.add("active");size=btn.dataset.size;const add=document.querySelector("[data-add]");add.disabled=false;add.textContent="In den Warenkorb"}));const add=document.querySelector("[data-add]");add?.addEventListener("click",()=>{if(!size)return;addToCart({id:root.dataset.id,name:root.dataset.name,price:Number(root.dataset.price),image:root.dataset.image,size});add.textContent="Hinzugefügt ✓";setTimeout(()=>add.textContent="In den Warenkorb",1200)})}
function renderCart(){const list=document.querySelector("[data-cart-list]");if(!list)return;let cart=getCart();const subtotalEl=document.querySelector("[data-subtotal]");const totalEl=document.querySelector("[data-total]");function draw(){list.innerHTML="";if(!cart.length){list.innerHTML='<div class="empty"><h2>Dein Warenkorb ist leer.</h2><p>Such dir im Shop dein Lieblingspiece aus.</p><a class="btn btn-primary" href="shop.html">Zum Shop</a></div>'}cart.forEach((item,index)=>{const row=document.createElement("article");row.className="cart-item";row.innerHTML=`<img src="${item.image}" alt=""><div><strong>${item.name}</strong><p class="muted">Grösse: ${item.size}</p><div class="price">${money(item.price)}</div><button class="icon-btn" data-remove="${index}" aria-label="Entfernen">×</button></div><div class="qty"><button data-minus="${index}">−</button><strong>${item.quantity||1}</strong><button data-plus="${index}">+</button></div>`;list.appendChild(row)});const subtotal=cart.reduce((s,i)=>s+i.price*(i.quantity||1),0);if(subtotalEl)subtotalEl.textContent=money(subtotal);if(totalEl)totalEl.textContent=money(subtotal);document.querySelector("[data-checkout]")?.toggleAttribute("hidden",!cart.length);saveCart(cart)}list.addEventListener("click",e=>{const plus=e.target.closest("[data-plus]"),minus=e.target.closest("[data-minus]"),remove=e.target.closest("[data-remove]");if(plus)cart[+plus.dataset.plus].quantity=(cart[+plus.dataset.plus].quantity||1)+1;if(minus){const i=+minus.dataset.minus;cart[i].quantity=Math.max(1,(cart[i].quantity||1)-1)}if(remove)cart.splice(+remove.dataset.remove,1);draw()});draw()}
function renderCheckout(){const box=document.querySelector("[data-order-summary]");if(!box)return;const cart=getCart();if(!cart.length){location.href="warenkorb.html";return}const total=cart.reduce((s,i)=>s+i.price*(i.quantity||1),0);box.innerHTML=cart.map(i=>`<div class="summary-row"><span>${i.quantity||1}× ${i.name} (${i.size})</span><strong>${money(i.price*(i.quantity||1))}</strong></div>`).join("")+`<div class="summary-row summary-total"><span>Total</span><span>${money(total)}</span></div>`;document.querySelector("[data-checkout-form]")?.addEventListener("submit",e=>{e.preventDefault();const order="EL-"+Date.now().toString().slice(-8);localStorage.setItem("elinaLastOrder",order);localStorage.removeItem(CART_KEY);location.href="danke.html"})}
document.addEventListener("DOMContentLoaded",()=>{updateCartBadge();initProductPage();renderCart();renderCheckout()});